'use strict';

const logger = require('./logger');

module.exports = {
    getVenueFromCourse: function(course) {
        switch (course) {
            case 'Aint':
                return "'Aintree'";
            case 'Ascot':
                return "'Ascot'";
            case 'Ayr':
                return "'Ayr'";
            case 'Bang':
                return "'Bangor'";
            case 'Ballin':
                return "'Ballinrobe'";
            case 'Bath':
                return "'Bath'";
            case 'Belle':
                return "'Bellewstown'";
            case 'Bev':
                return "'Beverley'";
            case 'Brig':
                return "'Brighton'";
            case 'Carl':
                return "'Carlisle'";
            case 'Cart':
                return "'Cartmel'";
            case 'Catt':
                return "'Catterick'";
            case 'Chelt':
                return "'Cheltenham'";
            case 'ChelmC':
                return "'Chelmsford City'";
            case 'Chep':
                return "'Chepstow'";
            case 'Chest':
                return "'Chester'";
            case 'Clon':
                return "'Clonmel'";
            case 'Cork':
                return "'Cork'";
            case 'Donc':
                return "'Doncaster'";
            case 'DownP':
                return "'Downpatrick'";
            case 'DownR':
                return "'Down Royal'";
            case 'Dund':
                return "'Dundalk'";
            case 'Epsm':
                return "'Epsom'";
            case 'Extr':
                return "'Exeter'";
            case 'Fairy':
                return "'Fairyhouse'";
            case 'Fake':
                return "'Fakenham'";
            case 'FfosL':
                return "'Ffos Las'";
            case 'Folk':
                return "'Folkstone'";
            case 'Font':
                return "'Fontwell'";
            case 'Gal':
                return "'Galway'";
            case 'Good':
                return "'Goodwood'";
            case 'GowP':
                return "'Gowran Park'";
            case 'Ham':
                return "'Hamilton'";
            case 'Hayd':
                return "'Haydock'";
            case 'Here':
                return "'Hereford'";
            case 'Hex':
                return "'Hexham'";
            case 'Hunt':
                return "'Huntingdon'";
            case 'Kelso':
                return "'Kelso'";
            case 'Kemp':
                return "'Kempton'";
            case 'Killar':
                return "'Killarney'";
            case 'Kilb':
                return "'Kilbeggan'";
            case 'Layt':
                return "'Laytown'";
            case 'Leic':
                return "'Leicester'";
            case 'Leic':
                return "'Leicester'";
            case 'Leop':
                return "'Leopardstown'";
            case 'Lim':
                return "'Limerick'";
            case 'List':
                return "'Listowel'";
            case 'Ludl':
                return "'Ludlow'";
            case 'MrktR':
                return "'Market Rasen'";
            case 'Muss':
                return "'Musselburgh'";
            case 'Naas':
                return "'Naas'";
            case 'Navan':
                return "'Navan'";
            case 'Newb':
                return "'Newbury'";
            case 'Newc':
                return "'Newcastle'";
            case 'Newm':
                return "'Newmarket'";
            case 'Newt':
                return "'Newton Abbot'";
            case 'Nott':
                return "'Nottingham'";
            case 'Perth':
                return "'Perth'";
            case 'Plump':
                return "'Plumpton'";
            case 'Ponte':
                return "'Pontefract'";
            case 'Punch':
                return "'Punchestown'";
            case 'Redc':
                return "'Redcar'";
            case 'Ripon':
                return "'Ripon'";
            case 'Rosc':
                return "'Roscommon'";
            case 'Salis':
                return "'Salisbury'";
            case 'Sand':
                return "'Sandown'";
            case 'Sedge':
                return "'Sedgefield'";
            case 'Shelb':
                return "'Shelbourne'";
            case 'Sligo':
                return "'Sligo'";
            case 'Sthl':
                return "'Southwell'";
            case 'Strat':
                return "'Stratford'";
            case 'Taun':
                return "'Taunton'";
            case 'Curr':
                return "'The Curragh'";
            case 'Thirsk':
                return "'Thirsk'";
            case 'Thurl':
                return "'Thurles'";
            case 'Tipp':
                return "'Tipperary'";
            case 'Towc':
                return "'Towcester'";
            case 'Tral':
                return "'Tralee'";
            case 'Tram':
                return "'Tramore'";
            case 'Uttox':
                return "'Uttoxeter'";
            case 'Warw':
                return "'Warwick'";
            case 'Weth':
                return "'Wetherby'";
            case 'Wex':
                return "'Wexford'";
            case 'Winc':
                return "'Wincanton'";
            case 'Wind':
                return "'Windsor'";
            case 'Wolv':
                return "'Wolverhampton'";
            case 'Worc':
                return "'Worcester'";
            case 'Yarm':
                return "'Yarmouth'";
            case 'York':
                return "'York'";
            default:
                logger.log('Unable to determine venue from course: ' + course, 'error');
                return null;
        }
    }
}